name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 */1 * * *'  # Cada 1 hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python scripts/update_thm.py

    - name: Commit changes if needed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git diff --cached --quiet || (git commit -m "Update TryHackMe badge" && git push)
